#!/usr/bin/env php
<?php


set_time_limit(0);

if(!ini_get('date.timezone')) {
    date_default_timezone_set('UTC');
}


// include the composer autoloader
require_once __DIR__ . '/../vendor/autoload.php';

// import the Console Application
use {{ name }}\Application;

$app = new Application();
$app->run();

?>